version: "3.7"
services:
    fairdata-download-auth:
        image: nginx
        restart: unless-stopped
        depends_on:
            - fairdata-download
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
            - ./secrets/.htpasswd:/etc/nginx/.htpasswd:ro
            - ./secrets/ssl.crt:/etc/nginx/ssl.crt:ro
            - ./secrets/ssl.key:/etc/nginx/ssl.key:ro
        networks:
            - downloadnetwork
        ports:
            - "4433:443"
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M

    fairdata-download:
        image: fairdownload:0.1.3
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile.prod
        networks:
            - downloadnetwork
        deploy:
            mode: replicated
            replicas: 2
            endpoint_mode: vip
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                limits:
                    cpus: '1.50'
                    memory: 2G
                reservations:
                    cpus: '0.5'
                    memory: 512M
#       logging:
#           driver: syslog
#           options:
#               syslog-address: "tcp://192.168.0.42:123"
        expose:
            - "8433"
        volumes:
            - type: bind
              source: ./secrets/metax.properties
              target: /opt/secrets/metax.properties
              read_only: true
            - type: bind
              source: ./service/application.properties
              target: /opt/login-download/config/application.properties
              read_only: true
            - type: bind
              source: ./service/config.properties
              target: /opt/login-download/config.properties
              read_only: true

networks:
    downloadnetwork:
