#########################################################
# Author(s):
#      Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# License: GPLv3
#
# (C) 2020 Copyright CSC - IT Center for Science Ltd.
# All Rights Reserved.
#########################################################
FROM openjdk:11
ADD logindownload.jar /opt/login-download/logindownload.jar
EXPOSE 8433
CMD cd /opt/login-download/ && java -Xmx6g -XX:MaxMetaspaceSize=180M -XX:MaxGCPauseMillis=5000 -jar logindownload.jar